### ISSUE TITLE
Documentation for prerelease

### ISSUE THREAD

**Issue by almereyda** [boringproxy/boringproxy.io#1]
After the first release of this software, new people arrive and like its approach to a no-frills, poor-man's VPN for exposing local web services easily.

From using it for about an hour, it becomes clear that a technical documentation is missing, that can help using the tool.

We have:

- The website at https://boringproxy.io/
- The Readme at https://github.com/boringproxy/boringproxy/blob/e93fc79f239caf3371386f22b1d4e2be6cb4fae7/README.md

From both together we can learn how to obtain the binary and how to run it in client and server scenarios.
That allows us to incrementally bring information blanks to our attention, that might not be immediately visible from the developer perspective.

Simple questions that one could ask the documentation already can be:

- How to login to the admin area. (Seriously.)
- How to set up a system service, a container or simply run it in a tmux session.
- How to create a user.
- How to create a token.
- How to establish a bridge.
- How to set up a service forward through the bridge.  
  To me it is not perfectly clear how I can address the LAN IP addresses at the remote end: Will I use the peer address, or will I use any address routeable within LAN?

More information we can give are the requirements to run:

- A system with a publicly routeable IP address and Ports 80 plus 443 free.

I'm happy to file a small PR that brings first additions regarding to my questions.

In a second step I would like to assist with self-documenting the executable, in so commands like `boringproxy -h/-help/--help`, `boringproxy -v/-version/--version` and `boringproxy` reveal meaningful output.

**Comment by almereyda** [comment]
I'm kind of documenting my steps that help me understanding and using this system. Why I'm adding a note here about the route

    https://outpost.test.io/login?access_token=

which is displayed upon first start of the server, to remind the admin where to look for the console. The token is stored in `boringproxy_db.json`. Finding this could also invite for a likely attempt of a volunteer to document the routes and verbs from the Go sources in an OpenAPI compatible format.

Further on a description of each key used in the JSON will help wrapping one's head around the semantics even more. From it I'm already learning, that the server of the tunnel somehow mentions `server_``address` and `port` bound to 22, yet that's where my SSHD is listening. Might there be a misconfiguration involved, that also influences https://github.com/boringproxy/boringproxy/issues/6?

**Comment by anderspitman** [comment]
Hey @almereyda, thanks yet again for your contributions. These are all great points. And of course you're right, there's a long way to go with documentation. I would gladly appreciate any PRs you're able to put together.

I hesitate to go too far documenting the REST API, until we have a better idea how it should work. The first version was fairly hacked together. I'd like to at least consider renaming a few of the returned attributes, and possibly removing some of them. One of my next tasks will be building a GUI client. That will be a good opportunity to exercise the API more fully and solidify it.

Can you provide more information about this:

> To me it is not perfectly clear how I can address the LAN IP addresses at the remote end: Will I use the peer address, or will I use any address routeable within LAN?

What's an example of what you're trying to do?

> From it I'm already learning, that the server of the tunnel somehow mentions server_``address and port bound to 22, yet that's where my SSHD is listening

Yeah it's not actually changing that information currently. The idea with this was the layer of indirection gives you more control over the tunnel setup. So for example you could do a geo lookup of the client's IP address, and then tell them to tunnel through an SSH server closer to their physical location to improve performance. Obviously there's no infrastructure in place to actually do that, and there's a good chance this is YAGNI.

**Comment by almereyda** [comment]
I have provided a first attempt at answering to the above requirements (by me ;) ) in #2 and hope it is a good base for discussion about how to structure the manual, while keeping a clear and figurative language.

I think it doesn't mention yet, that we need ports :80 and :443, plust that it expects OpenSSH to be present. That could be added after your first comments. For today that seems like a nice gift to this emerging now (https://github.com/boringproxy/boringproxy/pull/12) free and open source software.
