### ISSUE TITLE
Installation instructions should include other architectures besides amd64

### ISSUE THREAD

**Issue by luke2m** [boringproxy/boringproxy.io#5]
I will work on this soon.

**Comment by luke2m** [comment]
@anderspitman for Windows and macOS, do you just double click on the executable? Or is there some other setup that needs to be documented?

**Comment by anderspitman** [comment]
You would still need to run it from the command line. I've tested this on windows (shown in the demo video) but not mac. There will probably be a GUI client eventually but not in the short term.

**Comment by luke2m** [comment]
#6

**Comment by luke2m** [comment]
Fixed in #6
